[application]

# App (Project) Name
name = "rust-lecture"

# Dioxus App Default Platform
# web, desktop, fullstack
default_platform = "web"

# resource (assets) file folder
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "rust-lecture"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]

# include `assets` in web platform
[web.resource]


# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
